<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>
<h2>Usuários</h2>

<a class="pure-button" href="<?= $this->url(array("controller" => "usuario", "action" => "index"), null, true) ?>">Voltar</a>

<form class="pure-form pure-form-stacked cadastro-usuario" action="<?= $this->url(array("controller" => "usuario", "action" => "atualizar"), null, true) ?>" method="post">
    <fieldset>
        <legend>Editar Usuário</legend>
    
        <input type="hidden" name="idusuario" value="<?= $this->usuario['usu_id'] ?>" />

        <label for="nome">Nome</label>
        <input type="text" name="nome" id="nome" value="<?= $this->usuario['usu_nome']; ?>"/>

        <label for="login">Login</label>
        <input type="text" name="login" id="login" value="<?= $this->usuario['log_login']; ?>" disabled/>

        <label for="perfil">Perfil</label>
        <select name="perfil" id="perfil">
            <?php foreach ($this->perfis as $key => $perfil): ?>
                <option value="<?= $perfil['per_id']; ?>" <?= ($perfil['per_id'] == $this->usuario['per_id']) ? 'selected="selected"' : ''; ?>><?= $perfil['per_perfil']; ?></option>
            <?php endforeach; ?>
        </select>
        
        <label for="unidade_ensino">Unidade de Ensino</label>
        <select name="uni_id" id="unidade_ensino">
            <?php foreach ($this->unidadesEnsino as $key => $unidadeEnsino): ?>
                <option value="<?= $unidadeEnsino['uni_id']; ?>" <?= ($unidadeEnsino['uni_id'] == $this->usuario['uni_id']) ? 'selected="selected"' : ''; ?> ><?= $unidadeEnsino['uni_nome']; ?></option>
            <?php endforeach; ?>
        </select>

        <label for="email">E-mail</label>
        <input type="text" name="email" id="email" value="<?= $this->usuario['usu_email']; ?>"/>

        <label for="telefone">Telefone</label>
        <input type="text" name="telefone" id="telefone" class="telefone" value="<?= $this->usuario['usu_telefone']; ?>" />

        <button type="submit" class="pure-button pure-button-primary">Atualizar</button>
    
    </fieldset>

</form>