<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>
<h2>Usuários</h2>

<a class="pure-button" href="<?= $this->url(array("controller" => "usuario", "action" => "index"), null, true) ?>">Voltar</a>

<form class="pure-form pure-form-stacked" id="cadastro-usuario" action="<?= $this->url(array("controller" => "usuario", "action" => "criar"), null, true) ?>" method="post">
    <fieldset>
        <legend>Cadastrar Usuário</legend>
        
        <label for="nome">Nome</label>
        <input type="text" name="nome" id="nome" placeholder="Nome"/>
        
        <label for="login">Login</label>
        <input type="text" name="login" id="login" placeholder="Login"/>
        
        <label for="perfil">Perfil</label>
        <select name="perfil" id="perfil">
            <?php foreach ($this->perfis as $key => $perfil): ?>
                <option value="<?= $perfil['per_id']; ?>" ><?= $perfil['per_perfil']; ?></option>
            <?php endforeach; ?>
        </select>
        
        <label for="email">E-mail</label>
        <input type="text" name="email" id="email" placeholder="E-mail"/>
        
        <label for="telefone">Telefone</label>
        <input type="text" name="telefone" id="telefone" placeholder="Telefone" class="telefone" />

        <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
    </fieldset>
</form>