<?php
$this->headScript()->appendFile('/js/jquery.maskedinput.min.js');
$this->headScript()->appendFile('/js/mascaras.js');
?>
<h2>Alunos</h2>

<a class="pure-button" href="<?= $this->url(array("controller" => "turma", "action" => "visualizar", "id" => $this->aluno['tur_id']), null, true) ?>">Voltar</a>

<form class="pure-form pure-form-stacked cadastro-usuario" action="<?= $this->url(array("controller" => "aluno", "action" => "atualizar"), null, true) ?>" method="post">
    <fieldset>
        <legend>Editar Aluno</legend>
    
        <input type="hidden" name="alu_id" value="<?= $this->aluno['alu_id'] ?>" />

        <label for="nome">Nome</label>
        <input type="text" name="nome" id="nome" value="<?= $this->aluno['alu_nome']; ?>"/>
        
        <label for="data_nasc">Data Nascimento</label>
        <input type="text" name="data_nasc" id="data_nasc" value="<?= $this->aluno['alu_data_nasc']; ?>"/>
        
        <label for="sexo">Sexo</label>
        
        <label for="masculinho" class="pure-radio">
            <input id="masculinho" type="radio" name="sexo" value="M" <?= ($this->aluno['alu_sexo'] == 'M') ? 'checked' : ''; ?>>
            Masculino
        </label>
                
        <label for="feminino" class="pure-radio">
            <input id="feminino" type="radio" name="sexo" value="F" <?= ($this->aluno['alu_sexo'] == 'F') ? 'checked' : ''; ?>>
            Feminino
        </label>
        
        <label for="cpf">CPF</label>
        <input type="text" name="cpf" id="cpf" value="<?= $this->aluno['alu_cpf']; ?>"/>
        
        <label for="matricula">Matrícula</label>
        <input type="text" name="matricula" id="matricula" value="<?= $this->aluno['alu_matricula']; ?>"/>

        <label for="email">E-mail</label>
        <input type="text" name="email" id="email" value="<?= $this->aluno['alu_email']; ?>"/>

        <label for="telefone">Telefone</label>
        <input type="text" name="telefone" id="telefone" class="telefone" value="<?= $this->aluno['alu_telefone']; ?>" />
        
        <label for="celular">Celular</label>
        <input type="text" name="celular" id="celular" class="telefone" value="<?= $this->aluno['alu_celular']; ?>" />

        <button type="submit" class="pure-button pure-button-primary">Atualizar</button>
    
    </fieldset>

</form>