<div class="ui-widget" id="erro-login">
    <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
        <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .7em;"></span> 
        <strong>Erro:</strong> Login/Senha Inválidos! </p>
    </div>
</div>
<br />
<a class="pure-button" href="<?=$this->url(array("controller"=>"autenticacao","action"=>"index"),null,true)?>">Voltar</a>