<div id="login-form">
    <form class="pure-form pure-form-aligned" method="post" action="<?= $this->url(array('controller' => 'autenticacao', 'action' => 'login'), null, true) ?>">
        <fieldset>
            <div class="pure-control-group">
                <label for="login">Login</label>
                <input id="login" name="login" type="text" placeholder="Login">
            </div>

            <div class="pure-control-group">
                <label for="senha">Senha</label>
                <input id="senha" name="senha" type="password" placeholder="Senha">
            </div>

            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Entrar</button>
            </div>
        </fieldset>
    </form>
</div>