<h2>Unidades de Ensino</h2>

<a class="pure-button" href="<?= $this->url(array("controller" => "unidade-ensino", "action" => "novo"), null, true) ?>">Nova</a>
<br /><br />
<table class="pure-table pure-table-striped">
    <thead>
        <tr>
            <th>Unidade de Ensino</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->dados as $key => $unidadeEnsino):
        ?>
            <tr>
                <td><?= $unidadeEnsino['uni_nome'] ?></td>

                <td class="td-botao">
                    <a href="<?= $this->url(array("controller" => "unidade-ensino", "action" => "editar", "id" => $unidadeEnsino['uni_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Editar"><span class="ui-icon ui-icon-pencil"></span></li>
                        </ul>
                    </a>
                </td>
                <td class="td-botao">
                    <a href="<?= $this->url(array("controller" => "unidade-ensino", "action" => "excluir", "id" => $unidadeEnsino['uni_id']), null, true) ?>">
                        <ul id="icons" class="ui-widget ui-helper-clearfix">
                            <li class="ui-state-default ui-corner-all" title="Excluir"><span class="ui-icon ui-icon-close"></span></li>
                        </ul>
                    </a>
                </td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>